//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirPort
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timeline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Timeline()
        {
            this.Planes = new HashSet<Plane>();
        }
        public Timeline(TimeSpan _arrival, TimeSpan _depature)
        {
            arrival = _arrival;
            depature = _depature;
        }
    
        public int id { get; set; }
        public System.TimeSpan depature { get; set; }
        public System.TimeSpan arrival { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plane> Planes { get; set; }
    }
}
